### ISSUE TITLE
Before hook

### ISSUE THREAD

**Issue by lsoarestd** [ridiculous/object_tracker#1]
Is it possible to act on "method entering"? thanks

**Comment by ridiculous** [comment]
It's possible, sure. If you want the same hook to be called on every tracked method call, it's no problem. If you want to call certain hooks based on the method, it may be a bit tricky. 

How were you envisioning the API? Maybe: `object.track_all! before: ->(name, *args, &block) {}`

**Comment by lsoarestd** [comment]
I also thought of having `track_after` and `track_before`.
But in your proposal, how would you use it? Can you give an example?

**Comment by ridiculous** [comment]
I like the idea of having those hook methods (`track_after` and `track_before`). You think defining those on the tracked object, before extending ObjectTracker?

Here's an example of how you might use a proc to hook into method calls: https://github.com/ridiculous/object_tracker/pull/2

**Comment by ridiculous** [comment]
Try out the latest master and let me know what ya think

**Comment by lsoarestd** [comment]
I will try them now! thanks :)

**Comment by lsoarestd** [comment]
is there a way to turn off the puts? If I want to ad my logger, tracings or instrumentations I would not want to see the logger.

**Comment by ridiculous** [comment]
Oh, I never considered that. Makes a lot of sense though. We'd have to update it to accept a logger, and it could just default to STDOUT

**Comment by ridiculous** [comment]
It'd be easy to enable it as a config. I can add it (or if you want you), just something like:
```ruby
ObjectTracker.config.logger = Logger.new(STDOUT)
```

**Comment by ridiculous** [comment]
It's been implemented in __v2.1__ as `ObjectTracker.logger`, which you can override or set the level to ERROR. Let me know if it works for ya! Here's the [commit](https://github.com/ridiculous/object_tracker/commit/e4ffecb3675f792bba47db4358b47cd1207c4052) if you're curious
